### ISSUE TITLE
Finish Pages and add Development section to Readme

### ISSUE THREAD

**Issue by NickDruta** [NickDruta/MRSUTW#42]
Pages:
- Add Events in Homepage
- Events Page
- An event Page
- Admin Page for Events
- An event Page in Admin

**Comment by AnLuk13** [comment]
Add Events in Homepage finished

**Comment by AnLuk13** [comment]
Events Page finished

**Comment by AnLuk13** [comment]
An event Page finished

**Comment by AnLuk13** [comment]
Admin Page for Events
