### ISSUE TITLE
Finish Pages and add Description Section to Readme

### ISSUE THREAD

**Issue by NickDruta** [NickDruta/MRSUTW#44]
Pages:
- Orar Page
- Add Orar to HomePage
- Cauta Student Functionality
- Admin Page for Users

**Comment by vladdo001** [comment]
Orar Page Finished

**Comment by vladdo001** [comment]
Cauta Student Functionality finished

**Comment by vladdo001** [comment]
Add Orar to HomePage finished

**Comment by NickDruta** [comment]
Admin Page for Users finished

**Comment by vladdo001** [comment]
Admin Page for Users finished
